# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\nnene.voice\"\x1a\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\x0bTTSResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32M\n\nTTSService\x12?\n\nSynthesize\x12\x16.nene.voice.TTSRequest\x1a\x17.nene.voice.TTSResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=25
  _globals['_TTSREQUEST']._serialized_end=51
  _globals['_TTSRESPONSE']._serialized_start=53
  _globals['_TTSRESPONSE']._serialized_end=86
  _globals['_TTSSERVICE']._serialized_start=88
  _globals['_TTSSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
